export const content = [
  { name: "1", page: "Numbers", emoji: ".", filename: "1" },
  { name: "2", page: "Numbers", emoji: ". .", filename: "2" },
  { name: "3", page: "Numbers", emoji: ": .", filename: "3" },
  { name: "4", page: "Numbers", emoji: ": :", filename: "4" },
  { name: "5", page: "Numbers", emoji: ": : .", filename: "5" },
  { name: "6", page: "Numbers", emoji: ": : :", filename: "6" },
  { name: "7", page: "Numbers", emoji: ":::.", filename: "7" },
  { name: "8", page: "Numbers", emoji: "::::", filename: "8" },
  { name: "9", page: "Numbers", emoji: "::::.", filename: "9" },
  { name: "10", page: "Numbers", emoji: ":::::", filename: "10" },
  { name: "1", page: "ArabicNums", emoji: ".", filename: "1" },
  { name: "2", page: "ArabicNums", emoji: ". .", filename: "2" },
  { name: "3", page: "ArabicNums", emoji: ": .", filename: "3" },
  { name: "4", page: "ArabicNums", emoji: ": :", filename: "4" },
  { name: "5", page: "ArabicNums", emoji: ": : .", filename: "5" },
  { name: "6", page: "ArabicNums", emoji: ": : :", filename: "6" },
  { name: "7", page: "ArabicNums", emoji: ":::.", filename: "7" },
  { name: "8", page: "ArabicNums", emoji: "::::", filename: "8" },
  { name: "9", page: "ArabicNums", emoji: "::::.", filename: "9" },
  { name: "10", page: "ArabicNums", emoji: ":::::", filename: "10" },
  { name: "a", page: "Alphabets", emoji: "🍎", filename: "a" },
  { name: "b", page: "Alphabets", emoji: "🍌", filename: "b" },
  { name: "c", page: "Alphabets", emoji: "🐄", filename: "c" },
  { name: "d", page: "Alphabets", emoji: "🐶", filename: "d" },
  { name: "e", page: "Alphabets", emoji: "🐘", filename: "e" },
  { name: "f", page: "Alphabets", emoji: "🐠", filename: "f" },
  { name: "g", page: "Alphabets", emoji: "🦒", filename: "g" },
  { name: "h", page: "Alphabets", emoji: "🐔", filename: "h" },
  { name: "i", page: "Alphabets", emoji: "🍨", filename: "i" },
  { name: "j", page: "Alphabets", emoji: "🍹", filename: "j" },
  { name: "k", page: "Alphabets", emoji: "🦘", filename: "k" },
  { name: "l", page: "Alphabets", emoji: "🦁", filename: "l" },
  { name: "m", page: "Alphabets", emoji: "🐒", filename: "m" },
  { name: "n", page: "Alphabets", emoji: "💅🏻", filename: "n" },
  { name: "o", page: "Alphabets", emoji: "🦉", filename: "o" },
  { name: "p", page: "Alphabets", emoji: "🍽️", filename: "p" },
  { name: "q", page: "Alphabets", emoji: "❓", filename: "q" },
  { name: "r", page: "Alphabets", emoji: "🐇", filename: "r" },
  { name: "s", page: "Alphabets", emoji: "⭐", filename: "s" },
  { name: "t", page: "Alphabets", emoji: "🌳", filename: "t" },
  { name: "u", page: "Alphabets", emoji: "☂️", filename: "u" },
  { name: "v", page: "Alphabets", emoji: "🌋", filename: "v" },
  { name: "w", page: "Alphabets", emoji: "🍉", filename: "w" },
  { name: "x", page: "Alphabets", emoji: "❌", filename: "x" },
  { name: "y", page: "Alphabets", emoji: "🇾", filename: "y" },
  { name: "z", page: "Alphabets", emoji: "🦓", filename: "z" },
  { name: "أ", page: "Abjadia", emoji: "🐇", filename: "alef" },
  { name: "ب", page: "Abjadia", emoji: "🦆", filename: "baa" },
  { name: "ت", page: "Abjadia", emoji: "🍎", filename: "taa" },
  { name: "ث", page: "Abjadia", emoji: "🦊", filename: "tha" },
  { name: "ج", page: "Abjadia", emoji: "🐪", filename: "jim" },
  { name: "ح", page: "Abjadia", emoji: "🥛", filename: "hhaa" },
  { name: "خ", page: "Abjadia", emoji: "🐏", filename: "kha" },
  { name: "د", page: "Abjadia", emoji: "🐓", filename: "daa" },
  { name: "ذ", page: "Abjadia", emoji: "🌽", filename: "the" },
  { name: "ر", page: "Abjadia", emoji: "🧕🏻", filename: "raa" },
  { name: "ز", page: "Abjadia", emoji: "🦒", filename: "zaa" },
  { name: "س", page: "Abjadia", emoji: "🐿️", filename: "saa" },
  { name: "ش", page: "Abjadia", emoji: "🌞", filename: "shaa" },
  { name: "ص", page: "Abjadia", emoji: "🐥️", filename: "sad" },
  { name: "ض", page: "Abjadia", emoji: "🐸", filename: "dad" },
  { name: "ط", page: "Abjadia", emoji: "🦚", filename: "ttaa" },
  { name: "ظ", page: "Abjadia", emoji: "✉️", filename: "thaa" },
  { name: "ع", page: "Abjadia", emoji: "👁️", filename: "ayn" },
  { name: "غ", page: "Abjadia", emoji: "🌧️", filename: "ghayn" },
  { name: "ف", page: "Abjadia", emoji: "🦋", filename: "faa" },
  { name: "ق", page: "Abjadia", emoji: "🐒", filename: "qaf" },
  { name: "ك", page: "Abjadia", emoji: "📙", filename: "kaf" },
  { name: "ل", page: "Abjadia", emoji: "👅️", filename: "lam" },
  { name: "م", page: "Abjadia", emoji: "🍌", filename: "mim" },
  { name: "ن", page: "Abjadia", emoji: "🐝", filename: "non" },
  { name: "هـ", page: "Abjadia", emoji: "🎁", filename: "haa" },
  { name: "و", page: "Abjadia", emoji: "🌹", filename: "waw" },
  { name: "ي", page: "Abjadia", emoji: "📦", filename: "yaa" },
  { name: "🟥", page: "Colors", emoji: "🍎", filename: "red" },
  { name: "🟨", page: "Colors", emoji: "🌻", filename: "yellow" },
  { name: "🟩", page: "Colors", emoji: "🍏", filename: "green" },
  { name: "🟧", page: "Colors", emoji: "🏀", filename: "orange" },
  { name: "🟪", page: "Colors", emoji: "🍆", filename: "purple" },
  { name: "🟦", page: "Colors", emoji: "🐋", filename: "blue" },
  { name: "⬜", page: "Colors", emoji: "🏳️", filename: "white" },
  { name: "🟫", page: "Colors", emoji: "👜", filename: "brown" },
  { name: "⬛", page: "Colors", emoji: "🏴", filename: "black" },
  { name: "📐", page: "Shapes", emoji: "🔺", filename: "triangle" },
  { name: "🟥", page: "Shapes", emoji: "⬜", filename: "squar" },
  { name: "⭐", page: "Shapes", emoji: "🌟", filename: "star" },
  { name: "❤️", page: "Shapes", emoji: "🤍", filename: "heart" },
  { name: "⭕", page: "Shapes", emoji: "⚪", filename: "circle" }
];
