export const content = [
  { name: "1", page: "Numbers" },
  { name: "2", page: "Numbers" },
  { name: "3", page: "Numbers" },
  { name: "4", page: "Numbers" },
  { name: "5", page: "Numbers" },
  { name: "6", page: "Numbers" },
  { name: "7", page: "Numbers" },
  { name: "8", page: "Numbers" },
  { name: "9", page: "Numbers" },
  { name: "10", page: "Numbers" },
  { name: "a", page: "Alphabets", emoji: "🍎" },
  { name: "b", page: "Alphabets", emoji: "🍌" },
  { name: "c", page: "Alphabets", emoji: "🐄" },
  { name: "d", page: "Alphabets", emoji: "🐶" },
  { name: "e", page: "Alphabets", emoji: "🐘" },
  { name: "f", page: "Alphabets", emoji: "🐠" },
  { name: "g", page: "Alphabets", emoji: "🦒" },
  { name: "h", page: "Alphabets", emoji: "🐔" },
  { name: "i", page: "Alphabets", emoji: "🍨" },
  { name: "j", page: "Alphabets", emoji: "🍹" },
  { name: "k", page: "Alphabets", emoji: "🦘" },
  { name: "l", page: "Alphabets", emoji: "🦁" },
  { name: "m", page: "Alphabets", emoji: "🐒" },
  { name: "n", page: "Alphabets", emoji: "💅🏻" },
  { name: "o", page: "Alphabets", emoji: "🦉" },
  { name: "p", page: "Alphabets", emoji: "🍽️" },
  { name: "q", page: "Alphabets", emoji: "❓" },
  { name: "r", page: "Alphabets", emoji: "🐇" },
  { name: "s", page: "Alphabets", emoji: "⭐" },
  { name: "t", page: "Alphabets", emoji: "🌳" },
  { name: "u", page: "Alphabets", emoji: "☂️" },
  { name: "v", page: "Alphabets", emoji: "🌋" },
  { name: "w", page: "Alphabets", emoji: "🍉" },
  { name: "x", page: "Alphabets", emoji: "X" },
  { name: "y", page: "Alphabets", emoji: "🟡" },
  { name: "z", page: "Alphabets", emoji: "🦓" },
  { name: "أ", page: "Abjadia", emoji: "🐇" },
  { name: "ب", page: "Abjadia", emoji: "🦆" },
  { name: "ت", page: "Abjadia", emoji: "🍎" },
  { name: "ث", page: "Abjadia", emoji: "🦊" },
  { name: "ج", page: "Abjadia", emoji: "🐪" },
  { name: "ح", page: "Abjadia", emoji: "🥛" },
  { name: "خ", page: "Abjadia", emoji: "🐏" },
  { name: "د", page: "Abjadia", emoji: "🐓" },
  { name: "ذ", page: "Abjadia", emoji: "🌽" },
  { name: "ر", page: "Abjadia", emoji: "🧕🏻" },
  { name: "ز", page: "Abjadia", emoji: "🦒" },
  { name: "س", page: "Abjadia", emoji: "🐿️" },
  { name: "ش", page: "Abjadia", emoji: "🌞" },
  { name: "ص", page: "Abjadia", emoji: "🐥️" },
  { name: "ض", page: "Abjadia", emoji: "🐸" },
  { name: "ط", page: "Abjadia", emoji: "🦚" },
  { name: "ظ", page: "Abjadia", emoji: "✉️" },
  { name: "ع", page: "Abjadia", emoji: "👁️" },
  { name: "غ", page: "Abjadia", emoji: "🌧️" },
  { name: "ف", page: "Abjadia", emoji: "🦋" },
  { name: "ق", page: "Abjadia", emoji: "🐒" },
  { name: "ك", page: "Abjadia", emoji: "📙" },
  { name: "ل", page: "Abjadia", emoji: "👅️" },
  { name: "م", page: "Abjadia", emoji: "🍌" },
  { name: "ن", page: "Abjadia", emoji: "🐝" },
  { name: "هـ", page: "Abjadia", emoji: "🎁" },
  { name: "و", page: "Abjadia", emoji: "🌹" },
  { name: "ي", page: "Abjadia", emoji: "📦" }
];
